/// pray_calc_dart — Pure Dart Islamic prayer time calculation.
///
/// Implements the PrayCalc Dynamic Method: NREL SPA algorithm + MSC seasonal
/// algorithm + dynamic twilight angles.
///
/// Output is identical to the reference `pray-calc` TypeScript package, not merely close to
/// it. That is enforced rather than claimed: `test/parity_test.dart` asserts 282 vectors as
/// exact string matches against fixture output generated by the TypeScript side, spanning
/// fifteen locations, seven dates, both Asr conventions and all six high-latitude rules.
///
/// The wording here used to say "accurate to within 1 second", which was an estimate. When
/// the two ports were finally measured against each other they disagreed on 128 fields, by
/// up to 40 seconds on Fajr and two and a half minutes on Asr — the estimate had never been
/// checked. The fixture exists so that can never again be a matter of anyone's word.
library;

export 'src/types.dart';
export 'src/get_times.dart';
export 'src/get_times_all.dart';
export 'src/calc_times.dart';
export 'src/calc_times_all.dart';
export 'src/methods.dart';
export 'src/midnight.dart';
export 'src/constants.dart';
export 'src/angles.dart';
export 'src/solar_ephemeris.dart';
export 'src/msc.dart';
export 'src/asr.dart';
export 'src/qiyam.dart';
export 'src/high_latitude.dart';
export 'package:nrel_spa/nrel_spa.dart' show getSpa, SpaResult, SpaAnglesResult;
